"""Add browser_info to LoginLog

Revision ID: 5ba298f6c751
Revises: 4d347e07a546
Create Date: 2025-06-25 15:06:52.223046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba298f6c751'
down_revision = '4d347e07a546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browser_info', sa.String(length=255), nullable=True))
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('browser_info')

    # ### end Alembic commands ###
