from .bank_account_form import BankAccountForm
from .login_form import LoginForm
from .product_form import ProductForm
from .register_form import RegisterForm
from .forgot_password_form import ForgotPasswordForm
from .reset_password_form import ResetPasswordForm
from .attendance_form import AttendanceForm
from .register_form import RegisterForm
from .leave_form import LeaveRequestForm
from .payroll_form import PayrollForm
